module Motion
  module Iconic
    # Apparently, that means "persist" in Japanese
    # Source: http://www.japanesedictionary.org/search?search=persist&searchtype=english
    # I needed to find another name of "Constants"
    #  for compatibility issues with BubbleWrap (and
    #  potentially other gems)
    module Yaritousu
      ICONS = {
        awesome: [
          :glass, :music, :search, :envelopeO, :heart, :star, :starO, :user, :film, :thLarge, :th,
          :thList, :check, :times, :searchPlus, :searchMinus, :powerOff, :signal, :cog, :trashO, :home, :fileO,
          :clockO, :road, :download, :arrowCircleODown, :arrowCircleOUp, :inbox, :playCircleO, :repeat, :refresh, :listAlt, :lock,
          :flag, :headphones, :volumeOff, :volumeDown, :volumeUp, :qrcode, :barcode, :tag, :tags, :book, :bookmark,
          :print, :camera, :font, :bold, :italic, :textHeight, :textWidth, :alignLeft, :alignCenter, :alignRight, :alignJustify,
          :list, :outdent, :indent, :videoCamera, :pictureO, :pencil, :mapMarker, :adjust, :tint, :pencilSquareO, :shareSquareO,
          :checkSquareO, :arrows, :stepBackward, :fastBackward, :backward, :play, :pause, :stop, :forward, :fastForward, :stepForward,
          :eject, :chevronLeft, :chevronRight, :plusCircle, :minusCircle, :timesCircle, :checkCircle, :questionCircle, :infoCircle, :crosshairs, :timesCircleO,
          :checkCircleO, :ban, :arrowLeft, :arrowRight, :arrowUp, :arrowDown, :share, :expand, :compress, :plus, :minus,
          :asterisk, :exclamationCircle, :gift, :leaf, :fire, :eye, :eyeSlash, :exclamationTriangle, :plane, :calendar, :random,
          :comment, :magnet, :chevronUp, :chevronDown, :retweet, :shoppingCart, :folder, :folderOpen, :arrowsV, :arrowsH, :barChartO,
          :twitterSquare, :facebookSquare, :cameraRetro, :key, :cogs, :comments, :thumbsOUp, :thumbsODown, :starHalf, :heartO, :signOut,
          :linkedinSquare, :thumbTack, :externalLink, :signIn, :trophy, :githubSquare, :upload, :lemonO, :phone, :squareO, :bookmarkO,
          :phoneSquare, :twitter, :facebook, :github, :unlock, :creditCard, :rss, :hddO, :bullhorn, :bell, :certificate,
          :handORight, :handOLeft, :handOUp, :handODown, :arrowCircleLeft, :arrowCircleRight, :arrowCircleUp, :arrowCircleDown, :globe, :wrench, :tasks,
          :filter, :briefcase, :arrowsAlt, :users, :link, :cloud, :flask, :scissors, :filesO, :paperclip, :floppyO,
          :square, :bars, :listUl, :listOl, :strikethrough, :underline, :table, :magic, :truck, :pinterest, :pinterestSquare,
          :googlePlusSquare, :googlePlus, :money, :caretDown, :caretUp, :caretLeft, :caretRight, :columns, :sort, :sortAsc, :sortDesc,
          :envelope, :linkedin, :undo, :gavel, :tachometer, :commentO, :commentsO, :bolt, :sitemap, :umbrella, :clipboard,
          :lightbulbO, :exchange, :cloudDownload, :cloudUpload, :userMd, :stethoscope, :suitcase, :bellO, :coffee, :cutlery, :fileTextO,
          :buildingO, :hospitalO, :ambulance, :medkit, :fighterJet, :beer, :hSquare, :plusSquare, :angleDoubleLeft, :angleDoubleRight, :angleDoubleUp,
          :angleDoubleDown, :angleLeft, :angleRight, :angleUp, :angleDown, :desktop, :laptop, :tablet, :mobile, :circleO, :quoteLeft,
          :quoteRight, :spinner, :circle, :reply, :githubAlt, :folderO, :folderOpenO, :smileO, :frownO, :mehO, :gamepad,
          :keyboardO, :flagO, :flagCheckered, :terminal, :code, :replyAll, :mailReplyAll, :starHalfO, :locationArrow, :crop, :codeFork,
          :chainBroken, :question, :info, :exclamation, :superscript, :subscript, :eraser, :puzzlePiece, :microphone, :microphoneSlash, :shield,
          :calendarO, :fireExtinguisher, :rocket, :maxcdn, :chevronCircleLeft, :chevronCircleRight, :chevronCircleUp, :chevronCircleDown, :html5, :css3, :anchor,
          :unlockAlt, :bullseye, :ellipsisH, :ellipsisV, :rssSquare, :playCircle, :ticket, :minusSquare, :minusSquareO, :levelUp, :levelDown,
          :checkSquare, :pencilSquare, :externalLinkSquare, :shareSquare, :compass, :caretSquareODown, :caretSquareOUp, :caretSquareORight, :eur, :gbp, :usd,
          :inr, :jpy, :rub, :krw, :btc, :file, :fileText, :sortAlphaAsc, :sortAlphaDesc, :sortAmountAsc, :sortAmountDesc,
          :sortNumericAsc, :sortNumericDesc, :thumbsUp, :thumbsDown, :youtubeSquare, :youtube, :xing, :xingSquare, :youtubePlay, :dropbox, :stackOverflow,
          :instagram, :flickr, :adn, :bitbucket, :bitbucketSquare, :tumblr, :tumblrSquare, :longArrowDown, :longArrowUp, :longArrowLeft, :longArrowRight,
          :apple, :windows, :android, :linux, :dribbble, :skype, :foursquare, :trello, :female, :male, :gittip,
          :sunO, :moonO, :archive, :bug, :vk, :weibo, :renren, :pagelines, :stackExchange, :arrowCircleORight, :arrowCircleOLeft,
          :caretSquareOLeft, :dotCircleO, :wheelchair, :vimeoSquare, :try, :plusSquareO,
        ],
        foundation: [
          :addressBook, :alert, :alignCenter, :alignJustify, :alignLeft, :alignRight, :anchor, :annotate, :archive, :arrowDown,
          :arrowLeft, :arrowRight, :arrowUp, :arrowsCompress, :arrowsExpand, :arrowsIn, :arrowsOut, :asl, :asterisk, :atSign,
          :backgroundColor, :batteryEmpty, :batteryFull, :batteryHalf, :bitcoinCircle, :bitcoin, :blind, :bluetooth, :bold, :bookBookmark,
          :book, :bookmark, :braille, :burstNew, :burstSale, :burst, :calendar, :camera, :check, :checkbox,
          :clipboardNotes, :clipboardPencil, :clipboard, :clock, :closedCaption, :cloud, :commentMinus, :commentQuotes, :commentVideo, :comment,
          :comments, :compass, :contrast, :creditCard, :crop, :crown, :css3, :database, :dieFive, :dieFour,
          :dieOne, :dieSix, :dieThree, :dieTwo, :dislike, :dollarBill, :dollar, :download, :eject, :elevator,
          :euro, :eye, :fastForward, :femaleSymbol, :female, :filter, :firstAid, :flag, :folderAdd, :folderLock,
          :folder, :foot, :foundation, :graphBar, :graphHorizontal, :graphPie, :graphTrend, :guideDog, :hearingAid, :heart,
          :home, :html5, :indentLess, :indentMore, :info, :italic, :key, :laptop, :layout, :lightbulb,
          :like, :link, :listBullet, :listNumber, :listThumbnails, :list, :lock, :loop, :magnifyingGlass, :mail,
          :maleFemale, :maleSymbol, :male, :map, :marker, :megaphone, :microphone, :minusCircle, :minus, :mobileSignal,
          :mobile, :monitor, :mountains, :music, :next, :noDogs, :noSmoking, :pageAdd, :pageCopy, :pageCsv,
          :pageDelete, :pageDoc, :pageEdit, :pageExportCsv, :pageExportDoc, :pageExportPdf, :pageExport, :pageFilled, :pageMultiple, :pagePdf,
          :pageRemove, :pageSearch, :page, :paintBucket, :paperclip, :pause, :paw, :paypal, :pencil, :photo,
          :playCircle, :playVideo, :play, :plus, :pound, :power, :previous, :priceTag, :pricetagMultiple, :print,
          :prohibited, :projectionScreen, :puzzle, :quote, :record, :refresh, :resultsDemographics, :results, :rewindTen, :rewind,
          :rss, :safetyCone, :save, :share, :sheriffBadge, :shield, :shoppingBag, :shoppingCart, :shuffle, :skull,
          :social500px, :socialAdobe, :socialAmazon, :socialAndroid, :socialApple, :socialBehance, :socialBing, :socialBlogger, :socialDelicious, :socialDesignerNews,
          :socialDeviantArt, :socialDigg, :socialDribbble, :socialDrive, :socialDropbox, :socialEvernote, :socialFacebook, :socialFlickr, :socialForrst, :socialFoursquare,
          :socialGameCenter, :socialGithub, :socialGooglePlus, :socialHackerNews, :socialHi5, :socialInstagram, :socialJoomla, :socialLastfm, :socialLinkedin, :socialMedium,
          :socialMyspace, :socialOrkut, :socialPath, :socialPicasa, :socialPinterest, :socialRdio, :socialReddit, :socialSkillshare, :socialSkype, :socialSmashingMag,
          :socialSnapchat, :socialSpotify, :socialSquidoo, :socialStackOverflow, :socialSteam, :socialStumbleupon, :socialTreehouse, :socialTumblr, :socialTwitter, :socialVimeo,
          :socialWindows, :socialXbox, :socialYahoo, :socialYelp, :socialYoutube, :socialZerply, :socialZurb, :sound, :star, :stop,
          :strikethrough, :subscript, :superscript, :tabletLandscape, :tabletPortrait, :targetTwo, :target, :telephoneAccessible, :telephone, :textColor,
          :thumbnails, :ticket, :torsoBusiness, :torsoFemale, :torso, :torsosAllFemale, :torsosAll, :torsosFemaleMale, :torsosMaleFemale, :torsos,
          :trash, :trees, :trophy, :underline, :universalAccess, :unlink, :unlock, :uploadCloud, :upload, :usb,
          :video, :volumeNone, :volumeStrike, :volume, :web, :wheelchair, :widget, :wrench, :xCircle, :x,
          :yen, :zoomIn, :zoomOut,
        ],
        ion: [
          :alert, :alertCircled, :androidAdd, :androidAddContact, :androidAlarm, :androidArchive,
          :androidArrowBack, :androidArrowDownLeft, :androidArrowDownRight, :androidArrowUpLeft, :androidArrowUpRight, :androidBattery,
          :androidBook, :androidCalendar, :androidCall, :androidCamera, :androidChat, :androidCheckmark,
          :androidClock, :androidClose, :androidContact, :androidContacts, :androidData, :androidDeveloper,
          :androidDisplay, :androidDownload, :androidDropdown, :androidEarth, :androidFolder, :androidForums,
          :androidFriends, :androidHand, :androidImage, :androidInbox, :androidInformation, :androidKeypad,
          :androidLightbulb, :androidLocate, :androidLocation, :androidMail, :androidMicrophone, :androidMixer,
          :androidMore, :androidNote, :androidPlaystore, :androidPrinter, :androidPromotion, :androidReminder,
          :androidRemove, :androidSearch, :androidSend, :androidSettings, :androidShare, :androidSocial,
          :androidSocialUser, :androidSort, :androidStar, :androidStopwatch, :androidStorage, :androidSystemBack,
          :androidSystemHome, :androidSystemWindows, :androidTimer, :androidTrash, :androidVolume, :androidWifi,
          :archive, :arrowDownA, :arrowDownB, :arrowDownC, :arrowExpand,
          :arrowGraphDownLeft, :arrowGraphDownRight, :arrowGraphUpLeft, :arrowGraphUpRight, :arrowLeftA,
          :arrowLeftB, :arrowLeftC, :arrowMove, :arrowResize, :arrowReturnLeft,
          :arrowReturnRight, :arrowRightA, :arrowRightB, :arrowRightC, :arrowShrink,
          :arrowSwap, :arrowUpA, :arrowUpB, :arrowUpC, :at, :bag, :batteryCharging, :batteryEmpty, :batteryFull, :batteryHalf,
          :batteryLow, :beaker, :beer, :bluetooth, :bookmark, :briefcase, :bug, :calculator, :calendar, :camera,
          :card, :chatbox, :chatboxWorking, :chatboxes, :chatbubble,
          :chatbubbleWorking, :chatbubbles, :checkmark, :checkmarkCircled, :checkmarkRound,
          :chevronDown, :chevronLeft, :chevronRight, :chevronUp, :clipboard,
          :clock, :close, :closeCircled, :closeRound, :cloud, :code, :codeDownload, :codeWorking, :coffee, :compass,
          :compose, :connectionBars, :contrast, :disc, :document, :documentText, :drag, :earth, :edit, :egg,
          :eject, :email, :eye, :eyeDisabled, :female, :filing, :filmMarker, :flag, :flash, :flashOff,
          :flask, :folder, :fork, :forkRepo, :forward, :gameControllerA, :gameControllerB, :gearA, :gearB, :grid,
          :hammer, :headphone, :heart, :help, :helpBuoy, :helpCircled, :home, :icecream, :iconSocialGooglePlus, :iconSocialGooglePlusOutline,
          :image, :images, :information, :informationCircled, :ionic,
          :ios7Alarm, :ios7AlarmOutline, :ios7Albums, :ios7AlbumsOutline, :ios7ArrowBack,
          :ios7ArrowDown, :ios7ArrowForward, :ios7ArrowLeft, :ios7ArrowRight, :ios7ArrowThinDown,
          :ios7ArrowThinLeft, :ios7ArrowThinRight, :ios7ArrowThinUp, :ios7ArrowUp, :ios7At,
          :ios7AtOutline, :ios7Bell, :ios7BellOutline, :ios7Bolt, :ios7BoltOutline,
          :ios7Bookmarks, :ios7BookmarksOutline, :ios7Box, :ios7BoxOutline, :ios7Briefcase,
          :ios7BriefcaseOutline, :ios7Browsers, :ios7BrowsersOutline, :ios7Calculator, :ios7CalculatorOutline,
          :ios7Calendar, :ios7CalendarOutline, :ios7Camera, :ios7CameraOutline, :ios7Cart,
          :ios7CartOutline, :ios7Chatboxes, :ios7ChatboxesOutline, :ios7Chatbubble, :ios7ChatbubbleOutline,
          :ios7Checkmark, :ios7CheckmarkEmpty, :ios7CheckmarkOutline, :ios7CircleFilled, :ios7CircleOutline,
          :ios7Clock, :ios7ClockOutline, :ios7Close, :ios7CloseEmpty, :ios7CloseOutline,
          :ios7Cloud, :ios7CloudDownload, :ios7CloudDownloadOutline, :ios7CloudOutline, :ios7CloudUpload,
          :ios7CloudUploadOutline, :ios7Cloudy, :ios7CloudyNight, :ios7CloudyNightOutline, :ios7CloudyOutline,
          :ios7Cog, :ios7CogOutline, :ios7Compose, :ios7ComposeOutline, :ios7Contact,
          :ios7ContactOutline, :ios7Copy, :ios7CopyOutline, :ios7Download, :ios7DownloadOutline,
          :ios7Drag, :ios7Email, :ios7EmailOutline, :ios7Eye, :ios7EyeOutline,
          :ios7Fastforward, :ios7FastforwardOutline, :ios7Filing, :ios7FilingOutline, :ios7Film,
          :ios7FilmOutline, :ios7Flag, :ios7FlagOutline, :ios7Folder, :ios7FolderOutline,
          :ios7Gear, :ios7GearOutline, :ios7Glasses, :ios7GlassesOutline, :ios7Heart,
          :ios7HeartOutline, :ios7Help, :ios7HelpEmpty, :ios7HelpOutline, :ios7Infinite,
          :ios7InfiniteOutline, :ios7Information, :ios7InformationEmpty, :ios7InformationOutline, :ios7IonicOutline,
          :ios7Keypad, :ios7KeypadOutline, :ios7Lightbulb, :ios7LightbulbOutline, :ios7Location,
          :ios7LocationOutline, :ios7Locked, :ios7LockedOutline, :ios7Medkit, :ios7MedkitOutline,
          :ios7Mic, :ios7MicOff, :ios7MicOutline, :ios7Minus, :ios7MinusEmpty,
          :ios7MinusOutline, :ios7Monitor, :ios7MonitorOutline, :ios7Moon, :ios7MoonOutline,
          :ios7More, :ios7MoreOutline, :ios7MusicalNote, :ios7MusicalNotes, :ios7Navigate,
          :ios7NavigateOutline, :ios7Paperplane, :ios7PaperplaneOutline, :ios7Partlysunny, :ios7PartlysunnyOutline,
          :ios7Pause, :ios7PauseOutline, :ios7People, :ios7PeopleOutline, :ios7Person,
          :ios7PersonOutline, :ios7Personadd, :ios7PersonaddOutline, :ios7Photos, :ios7PhotosOutline,
          :ios7Pie, :ios7PieOutline, :ios7Play, :ios7PlayOutline, :ios7Plus,
          :ios7PlusEmpty, :ios7PlusOutline, :ios7Pricetag, :ios7PricetagOutline, :ios7Printer,
          :ios7PrinterOutline, :ios7Rainy, :ios7RainyOutline, :ios7Recording, :ios7RecordingOutline,
          :ios7Redo, :ios7RedoOutline, :ios7Refresh, :ios7RefreshEmpty, :ios7RefreshOutline,
          :ios7Reload, :ios7Rewind, :ios7RewindOutline, :ios7Search, :ios7SearchStrong,
          :ios7Skipbackward, :ios7SkipbackwardOutline, :ios7Skipforward, :ios7SkipforwardOutline, :ios7Snowy,
          :ios7Speedometer, :ios7SpeedometerOutline, :ios7Star, :ios7StarOutline, :ios7Stopwatch,
          :ios7StopwatchOutline, :ios7Sunny, :ios7SunnyOutline, :ios7Telephone, :ios7TelephoneOutline,
          :ios7Thunderstorm, :ios7ThunderstormOutline, :ios7Time, :ios7TimeOutline, :ios7Timer,
          :ios7TimerOutline, :ios7Trash, :ios7TrashOutline, :ios7Undo, :ios7UndoOutline,
          :ios7Unlocked, :ios7UnlockedOutline, :ios7Upload, :ios7UploadOutline, :ios7Videocam,
          :ios7VideocamOutline, :ios7VolumeHigh, :ios7VolumeLow, :ios7Wineglass, :ios7WineglassOutline,
          :ios7World, :ios7WorldOutline, :ipad, :iphone, :ipod,
          :jet, :key, :knife, :laptop, :leaf, :levels, :lightbulb, :link, :loadA, :loadB,
          :loadC, :loadD, :location, :locked, :logIn, :logOut, :loop, :magnet, :male, :man,
          :map, :medkit, :micA, :micB, :micC, :minus, :minusCircled, :minusRound, :modelS, :monitor,
          :more, :musicNote, :navicon, :naviconRound, :navigate, :noSmoking, :nuclear, :paperAirplane, :paperclip, :pause,
          :person, :personAdd, :personStalker, :pieGraph, :pin, :pinpoint, :pizza, :plane, :play, :playstation,
          :plus, :plusCircled, :plusRound, :pound, :power, :pricetag, :pricetags, :printer, :radioWaves, :record,
          :refresh, :reply, :replyAll, :search, :settings, :share, :shuffle, :skipBackward, :skipForward, :socialAndroid,
          :socialAndroidOutline, :socialApple, :socialAppleOutline, :socialBitcoin, :socialBitcoinOutline,
          :socialBuffer, :socialBufferOutline, :socialDesignernews, :socialDesignernewsOutline, :socialDribbble,
          :socialDribbbleOutline, :socialDropbox, :socialDropboxOutline, :socialFacebook, :socialFacebookOutline,
          :socialFreebsdDevil, :socialGithub, :socialGithubOutline, :socialGoogleplus, :socialGoogleplusOutline,
          :socialHackernews, :socialHackernewsOutline, :socialLinkedin, :socialLinkedinOutline, :socialPinterest,
          :socialPinterestOutline, :socialReddit, :socialRedditOutline, :socialRss, :socialRssOutline,
          :socialSkype, :socialSkypeOutline, :socialTumblr, :socialTumblrOutline, :socialTux,
          :socialTwitter, :socialTwitterOutline, :socialVimeo, :socialVimeoOutline, :socialWindows,
          :socialWindowsOutline, :socialWordpress, :socialWordpressOutline, :socialYahoo, :socialYahooOutline,
          :socialYoutube, :socialYoutubeOutline, :speakerphone, :speedometer, :spoon,
          :star, :statsBars, :steam, :stop, :thermometer, :thumbsdown, :thumbsup, :trashA, :trashB, :umbrella,
          :unlocked, :upload, :usb, :videocamera, :volumeHigh, :volumeLow, :volumeMedium, :volumeMute, :waterdrop, :wifi,
          :wineglass, :woman, :wrench, :xbox,
        ],
        zocial: [
          :acrobat, :amazon, :android, :angellist, :aol, :appnet, :appstore, :bitbucket, :bitcoin, :blogger,
          :buffer, :call, :cal, :cart, :chrome, :cloudapp, :creativecommons, :delicious, :digg, :disqus,
          :dribbble, :dropbox, :drupal, :dwolla, :email, :eventasaurus, :eventbrite, :eventful, :evernote, :facebook,
          :fivehundredpx, :flattr, :flickr, :forrst, :foursquare, :github, :gmail, :google, :googleplay, :googleplus,
          :gowalla, :grooveshark, :guest, :html5, :ie, :instagram, :instapaper, :intensedebate, :itunes, :klout,
          :lanyrd, :lastfm, :lego, :linkedin, :lkdto, :logmein, :macstore, :meetup, :myspace, :ninetyninedesigns,
          :openid, :opentable, :paypal, :pinboard, :pinterest, :plancast, :plurk, :pocket, :podcast, :posterous,
          :print, :quora, :reddit, :rss, :scribd, :skype, :smashing, :songkick, :soundcloud, :spotify,
          :stackoverflow, :statusnet, :steam, :stripe, :stumbleupon, :tumblr, :twitter, :viadeo, :vimeo, :vk,
          :weibo, :wikipedia, :windows, :wordpress, :xing, :yahoo, :ycombinator, :yelp, :youtube,
        ]
      }
    end
  end
end
